{{- include "ffc-helm-library.container-config-map" (list . "ffc-grants-desirability-notification.config-map") -}}
{{- define "ffc-grants-desirability-notification.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  PORT: {{ quote .Values.container.port }}
  NOTIFY_API_KEY: {{ quote .Values.container.notifyApiKey }}
  DESIRABILITY_SUBMITTED_TOPIC_ADDRESS: {{ quote .Values.container.desirabilitySubmittedTopicAddress }}
  DESIRABILITY_SUBMITTED_SUBSCRIPTION_ADDRESS: {{ quote .Values.container.desirabilitySubmittedSubscriptionAddress }}
  SERVICE_BUS_HOST: {{ quote .Values.container.messageQueueHost }}
{{- end -}}
