{{- include "ffc-helm-library.container-secret" (list . "ffc-grants-desirability-notification-container-secret") -}}
{{- define "ffc-grants-desirability-notification-container-secret" -}}
stringData:
  APPINSIGHTS_INSTRUMENTATIONKEY: {{ .Values.appInsights.key | quote }}
{{- end -}}