{{- include "ffc-helm-library.deployment" (list . "ffc-grants-desirability-notification.deployment") -}}
{{- define "ffc-grants-desirability-notification.deployment" -}}
spec:
  template:
    spec:
      containers:
      - {{ include "ffc-helm-library.container" (list . "ffc-grants-desirability-notification.container") }}
{{- end -}}
