version: '3.8'

services:
  ffc-grants-desirability-notification:
    build:
      context: .
      target: production
    image: ffc-grants-desirability-notification
    container_name: ffc-grants-desirability-notification
    environment:
      NOTIFY_API_KEY: ${NOTIFY_API_KEY:-notset}
