apiVersion: v2
description: Notification sender for submitted EOIs
name: ffc-grants-desirability-notification
# this version is automatically updated in the build pipline
version: 1.0.0
dependencies:
- name: ffc-helm-library
  version: ^2.5.2
  repository: https://raw.githubusercontent.com/defra/ffc-helm-repository/master/
